capture:
  source: 0
  resize_width: 800

sift:
  nfeatures: 500

corner_selection:
  row_white_ratio: 0.50
  column_white_ratio: 0.50
  corner_search_radius: 40

warp:
  output_width: 800
  output_height: 1100
  interpolation: "linear"